data:
  raw: data/raw
  processed: data/processed
  features: data/features

train:
  test_size: 0.2
  random_state: 42
  scale: true

model:
  type: RandomForestClassifier
  n_estimators: 100
  max_depth: 5
